### ISSUE TITLE
Null reference?

### ISSUE THREAD

**Issue by ddres0605** [allanpichardo/Unity-Beat-Detection#1]
Using the example script I keep getting this error

NullReferenceException: Object reference not set to an instance of an object
AudioProcessor.addAudioCallback (AudioCallbacks callback) (at Assets/Hztest/AudioProcessor.cs:323)
Example.Start () (at Assets/Hztest/Example.cs:30)

I have no idea how any of this stuff works.

**Comment by allanpichardo** [comment]
Hi,

Add an audio source with a sound to your main camera and attach the
AudioProcessor script to the main camera.

If you look at the start() method of the Example script, you'll notice that
it's searching for an active instance of the AudioProcessor

AudioProcessor processor = FindObjectOfType<AudioProcessor>();


That's where the error happens. It seems that when
FindObjectOfType<AudioProcessor>() executes, it can't find an instance.

I hope this helps you. I know my instructions are pretty low-level, but
this class is intended for programmers who are familiar with
object-oriented programming. Basically, the AudioProcessor is an object
that is instantiated once and runs continually processing the audio source
that it's attached to. Whenever it detects an audio event, such as a beat,
it calls one of its virtual functions, which you must implement yourself.

**Comment by ddres0605** [comment]
Yeah I have that setup. I've fixed it by adding a wait in between the two lines of code in the start.

**Comment by matthew-p** [comment]
I had the same thing happen, this wait implementation fixed it. Is there a better way? 
```

public class BeatBehavior : MonoBehaviour, AudioProcessor.AudioCallbacks
{
    IEnumerator Start()
    {
        //Select the instance of AudioProcessor and pass a reference
        //to this object
        Debug.Log(this.name);
        AudioProcessor processor = FindObjectOfType<AudioProcessor>();
        yield return new WaitForSeconds(0.5f);
        processor.addAudioCallback(this);
    }
```

**Comment by allanpichardo** [comment]
Hmm...I'll look into it. It's about due time for an update. I'll let you
know.
