### ISSUE TITLE
Spectrum Array allocation in Update function

### ISSUE THREAD

**Issue by dimixar** [allanpichardo/Unity-Beat-Detection#2]
It's not really an issue, but some tips for optimizations.

In function Update, you allocate every frame a new array for spectrum. That's not a really good idea. You don't need to allocate every time a new array of floats. Allocation every frame is a very expensive operation in C#.

Also the function ComputeAveragers() is returning a new array every time, which also can be a potential bottleneck, because again allocation every frame is a very expensive operation in C#.

Also in Update(), array acVals has a new array allocated every frame.

P.S. There is one more thing. You're calling function GetComponent<>() every frame. GetComponent<>() is also a expensive function. Better having a variable of AudioSource in class and in start getting it. Then you use only that variable.

**Comment by allanpichardo** [comment]
Thanks. I haven't had much time to update this. I'll do this when I have some time. Or, you can submit a pull request with these changes if you'd like.

**Comment by dimixar** [comment]
Ok, I'll make a pull request.
This is what happens in the profiler before the optimizations:
![Image before optimizations]
(http://goo.gl/2JAXa7)

And this is after the optimizations:
![Image after optimizations]
(http://goo.gl/BGNv3k)

The allocations are a lot less.
