### ISSUE TITLE
Need we include the Apache 2.0 copyright or attribute the author in the credits?

### ISSUE THREAD

**Issue by kusokuso1** [allanpichardo/Unity-Beat-Detection#7]
If I sell a game (not necessarily a music game, but an action game) that uses this package, must I include reference/copyright info for it in the credits?  Only thing I could find related to copyrights was the Apache 2.0 license.

Thanks!

**Comment by allanpichardo** [comment]
Hi,

This library is licenced under the Apache 2.0 licence so yes, an
attribution should be included as well as the license notice on the source
file.

Here's a short description of the main points of the license, count be
helpful:
https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

I hope that helps!

I love to see what people make with the library so feel free to share a
link to your game if you publish it.

-Allan

**Comment by kusokuso1** [comment]
Wow, you're fast!  Thanks for the info and links.
I always give credit where it is due!  Thanks, again, for your time!
